import { Docx_Text } from "./WordComponents/Text";
import { Docx_Paragraph } from "./WordComponents/Paragraph";
import { Docx_Image } from "./WordComponents/Image";
import { Docx } from "./Services/Docx";
import { Docx_Document } from "./WordComponents/Document";
import { Zip } from "./Services/Zip";

Docx.createContentTypesFile();
Docx.createRelationshipFolder();
Docx.CreateWordFolder({
  imagesFilePath: "./Images",
  document: (
    Docx_Document([
      Docx_Paragraph([
        Docx_Text({ bold: true, text: "bold text" }),
        Docx_Text({ italic: true, text: "italic text" }),
        Docx_Text({ text: "underlined text" }),
        Docx_Text({ text: "normal text" }),
        Docx_Text({ bold: true, italic: true, text: "bold & italic text" }),
        Docx_Text({ bold: true, text: `bold & "underlined" text` }),
        Docx_Text({ italic: true,  text:  `U+0000–U+001F` }),
        Docx_Text({ bold: true, italic: true, text: `U+D800–U+DFFF` }),
        Docx_Text({ text: "U+FFFE" }),
        Docx_Text({ text: "normal text" }),
      ]),
      Docx_Paragraph([Docx_Text({ text: "cat.jpg" })]),
      Docx_Image("cat.jpg", { width: 1024, height: 1536 }),
      Docx_Paragraph([Docx_Text({ text: "Square distorted io.jpg" })]),
      Docx_Image("io.jpg", { width: 3, height: 3 }),
      Docx_Paragraph([Docx_Text({ text: "io2.jpg" })]),
      Docx_Image("io2.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io3.jpg" })]),
      Docx_Image("io3.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io4.jpg" })]),
      Docx_Image("io4.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io5.jpg" })]),
      Docx_Image("io5.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io6.jpg" })]),
      Docx_Image("io6.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io7.jpg" })]),
      Docx_Image("io7.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io8.jpg" })]),
      Docx_Image("io8.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io9.jpg" })]),
      Docx_Image("io9.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io10.jpg" })]),
      Docx_Image("io10.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io11.jpg" })]),
      Docx_Image("io11.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io12.jpg" })]),
      Docx_Image("io12.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io13.jpg" })]),
      Docx_Image("io13.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io14.jpg" })]),
      Docx_Image("io14.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io15.jpg" })]),
      Docx_Image("io15.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io16.jpg" })]),
      Docx_Image("io16.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io17.jpg" })]),
      Docx_Image("io17.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io18.jpg" })]),
      Docx_Image("io18.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io19.jpg" })]),
      Docx_Image("io19.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io20.jpg" })]),
      Docx_Image("io20.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io21.jpg" })]),
      Docx_Image("io21.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io22.jpg" })]),
      Docx_Image("io22.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io23.jpg" })]),
      Docx_Image("io23.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io24.jpg" })]),
      Docx_Image("io24.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io25.jpg" })]),
      Docx_Image("io25.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io26.jpg" })]),
      Docx_Image("io26.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io27.jpg" })]),
      Docx_Image("io27.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io28.jpg" })]),
      Docx_Image("io28.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io29.jpg" })]),
      Docx_Image("io29.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io30.jpg" })]),
      Docx_Image("io30.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io31.jpg" })]),
      Docx_Image("io31.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io32.jpg" })]),
      Docx_Image("io32.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io33.jpg" })]),
      Docx_Image("io33.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io34.jpg" })]),
      Docx_Image("io34.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io35.jpg" })]),
      Docx_Image("io35.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io36.jpg" })]),
      Docx_Image("io36.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io37.jpg" })]),
      Docx_Image("io37.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io38.jpg" })]),
      Docx_Image("io38.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io39.jpg" })]),
      Docx_Image("io39.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io40.jpg" })]),
      Docx_Image("io40.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io41.jpg" })]),
      Docx_Image("io41.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io42.jpg" })]),
      Docx_Image("io42.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io43.jpg" })]),
      Docx_Image("io43.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io44.jpg" })]),
      Docx_Image("io44.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io45.jpg" })]),
      Docx_Image("io45.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io46.jpg" })]),
      Docx_Image("io46.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io47.jpg" })]),
      Docx_Image("io47.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io48.jpg" })]),
      Docx_Image("io48.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io49.jpg" })]),
      Docx_Image("io49.jpg", { width: 3, height: 2 }),
      Docx_Paragraph([Docx_Text({ text: "io50.jpg" })]),
      Docx_Image("io50.jpg", { width: 3, height: 2 }),
    ])
  )
})
Zip.createDocx("docx_output.docx");
